server:
  port: 8080

spring:
  application:
    name: zalo-clone

  profiles:
    active: dev

  # Cấu hình MongoDB Atlas
  data:
    mongodb:
      uri: mongodb+srv://admin:12345@cluster0.8vnkcd6.mongodb.net/zalo_chat?retryWrites=true&w=majority
      auto-index-creation: true

    # Cấu hình Redis
#    redis:
#      host: localhost
#      port: 6379

  # Cấu hình Gửi Mail (Dùng App Password của Google)
  mail:
    host: smtp.gmail.com
    port: 587
    username: theanh199405023@gmail.com
    password: lbwcahcnaealcyzb
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  # Cấu hình File Upload
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # Cấu hình Gemini AI (Sử dụng qua OpenAI SDK)
#  ai:
#    openai:
#      api-key: ${GEMINI_API_KEY}
#      base-url: "https://generativelanguage.googleapis.com/v1beta/openai"
#      chat:
#        options:
#          model: "gemini-1.5-flash-latest"
#          temperature: 0.7

  # Định dạng ngày tháng
  jackson:
    serialization:
      write-dates-as-timestamps: false

# Swagger documentation
#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true

# Bảo mật JWT
jwt:
  secretKey: "UGV0b3BpYS1Qcm9qZWN0LVNlY3JldC1LZXktRm9yLUpXVC1HZW5lcmF0aW9uLVZlcnktU2VjdXJlLUFuZC1Mb25n"
  expiration: 86400000          # 1 ngày
  refresh-expiration: 604800000 # 7 ngày

# Cloudinary (Lưu trữ ảnh/video)
cloudinary:
  cloud_name: "dybv2kwhk"
  api_key: "828476781652141"
  api_secret: "KNJf4ivOJ-aZ7jwlfrrxria-xWs"

logging:
  level:
    root: INFO
    org.springframework.data.mongodb: DEBUG # Để theo dõi query Mongo